### ISSUE TITLE
some thinks

### ISSUE THREAD

**Issue by Risa123** [Cr0s/WarpDrive#48]
Zoom on left click not good idea.  I think.

No compatibility with tileEntities why ? TileEntity is frekventaly in all mods.

Sorry for my english.

**Comment by LemADEC** [comment]
Wrong place to report issues.
No version provided, can't help you.
TileEntities are supported.

**Comment by Risa123** [comment]
wrong place ?

**Comment by Risa123** [comment]
My version is latest.

**Comment by Risa123** [comment]
and i cant use warp or hyperspace jump when tileEntity on my ship

**Comment by LemADEC** [comment]
Open your issue in the current repo, here: https://github.com/LemADEC/WarpDrive/issues/new

**Comment by Risa123** [comment]
Ok
