### ISSUE TITLE
WarpDrive-1.7.10-1.3.29.- Incompatible with DraconicEvolution EnergyCore

### ISSUE THREAD

**Issue by limmers2015** [Cr0s/WarpDrive#52]
I am trying to power a ship with a DraaconicEvolution tier 4 EnergyCore. I have a working and verified power conversion setup from RF to EU. Every time I move the ship, I have to break and replace the core, losing almost 10 billion RF. Is there something that you can do to fix this, or something that you can tell me to do? Thanks

P.S.     I can't and won't update to a higher minecraft version. And I'm playing a custom mix of forge mods. If the info on them is needed to solve this, I can find that too.

Thank you again.

**Comment by LemADEC** [comment]
WarpDrive already supports RF, no need to convert it to EU.
I need the full mod list with version, or simply a copy of your modpack folder including the world save and coordinates of your ship.

**Comment by LemADEC** [comment]
Also, this is not the proper repository, please open your issue on https://github.com/LemADEC/WarpDrive/issues

**Comment by limmers2015** [comment]
Sorry about that. Switched to new repository.
