### ISSUE TITLE
How to find/get to a planet with Warpdrive mod

### ISSUE THREAD

**Issue by ScathaIsTheBest101** [Cr0s/WarpDrive#54]
I need help with finding and geting to a planet with the warpdrive mod! I have been on minecraft for like an hour trying to find one and get to one! Can someone please help me? Thanks!

**Comment by LemADEC** [comment]
Please use the proper github for support. => https://github.com/LemADEC/WarpDrive/issues as linked in the official forum and curseforge page.

**Comment by ScathaIsTheBest101** [comment]
OK! Thanks!
